"""Save/load images: the private Supabase Storage bucket when SUPABASE_URL is set, otherwise backend/uploads/
on disk (local development and the offline-demo fallback; that folder is git-ignored).

Paths are always generated by the app (uuid names), never taken from the user's filename.
"""
import functools
from pathlib import Path

from app.core.config import get_settings

LOCAL_DIR = Path(__file__).resolve().parents[2] / "uploads"


@functools.cache
def _bucket():
    from supabase import create_client

    s = get_settings()
    return create_client(s.supabase_url, s.supabase_service_key).storage.from_(s.storage_bucket)


def save(path: str, data: bytes, content_type: str) -> None:
    if get_settings().supabase_url:
        _bucket().upload(path, data, {"content-type": content_type})
    else:
        f = LOCAL_DIR / path
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_bytes(data)


def load(path: str) -> bytes:
    if get_settings().supabase_url:
        return _bucket().download(path)
    return (LOCAL_DIR / path).read_bytes()
